app/admin/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, session, current_app, render_template, json
from flask.ext.login import login_required, LoginManager, current_user
from app.socketio_ns import ShoutNamespace
import re

import pymongo
from bson.objectid import ObjectId

from app import json_util, db, TW_Client
from app.resources.prefs import Preferences
from app.resources.theme import ThemeList
from app.resources.race import RaceList
from app.twitter.resources import Me

mod = Blueprint('admin', __name__, url_prefix='/admin')

races = db['races']

json_dump = lambda data: json.dumps(data, default=json_util.default)

@mod.context_processor
def inject_twitter_account():
    if 'API_KEY' in current_app.config and current_app.config['API_KEY']:
        twitter_account = Me()
        return dict(twitter_account=json_dump( twitter_account.get() ) )
    return dict()

@mod.context_processor
def inject_themes():
    theme_list = ThemeList()
    return dict(themes=json_dump( theme_list.get() ))

@mod.context_processor
def inject_races():
    race_list = RaceList()
    return dict(races=json_dump( race_list.get() ))

@mod.context_processor
def inject_infos():
    return dict(level='private', is_admin=current_user.is_admin(), 
                server_info=current_app.config['SERVER_CONFIG'],
                bucket=current_app.config['S3_BUCKET_NAME'] )

@mod.route("/")
@login_required
def admin():
    return render_template("admin.html")



# @todo: devrait etre en resources 
@mod.route("/devices")
@login_required
def get_devices():
    # devices en attente
    devices = [ {'id': id(ws), 'room': 'waiting', 'race_id': '', 'race_title': 'En attente'} 
                for ws in ShoutNamespace.sockets.values() 
                if "/shouts_waiting" in ws.session['rooms'] ]
    
    # devices connectés sur un Live public
    for ws in ShoutNamespace.sockets.values():
        for room in ws.session['rooms']:
            reg_play = re.match(r'(/shouts_play_)([a-f0-9]{24})\b', room)
            if reg_play:
                race = races.find_one({'_id': ObjectId(reg_play.group(2)) })
                devices.append({'id': id(ws), 'room': "play_%s" % reg_play.group(2), 'race_id': race['_id'], 'race_title': race['title']})

    return json_dump( devices )

app/user/views.py
# -*- coding: utf-8 -*-
from flask import Blueprint, request, render_template, redirect, flash, url_for
from flask.ext.login import LoginManager, login_required, login_user, logout_user, current_user
import pymongo
from bson.objectid import ObjectId
from app.user.model import User
import bcrypt
from app import app, db, load_user

mod = Blueprint('user', __name__, url_prefix='/user')

users = db['users']


@mod.route("/login", methods=['GET','POST'])
def login():
    if request.method == 'GET':
        if not users.count():
            return redirect(url_for('.firstregister'))

        return render_template('login.html')

    username = request.form['username']
    password = request.form['password']
    registered_user = users.find_one({'username': username})

    if bcrypt.hashpw(password, registered_user['password']) == registered_user['password']:
        user = load_user(registered_user['_id'])
        login_user(user)
        print current_user
        flash('Vous êtes authentifié')
    else:
        flash('Le login ou le password sont invalides' , 'error')
        return redirect(url_for('.login'))

    return redirect(request.args.get('next') or '/')


@mod.route("/logout")
@login_required
def logout():
    logout_user()
    # session.pop('user')
    return redirect(url_for('.login'))


@mod.route('/register' , methods=['GET','POST'])
@login_required
def register():
    if request.method == 'GET':
        return render_template('register.html')

    registered_user = users.find_one({'username': request.form['username']})

    if registered_user is None:
        user = User(None, request.form['username'] , request.form['password'], request.form['email'], 0)
        users.insert(user.__dict__)
        flash('User successfully registered')
        return redirect(url_for('.login'))
    else:
        flash('Ce username est déjà pris' , 'error')
        return redirect(url_for('.register'))


@mod.route('/welcome' , methods=['GET','POST'])
def firstregister():
    if users.count():
        return redirect(url_for('.login'))

    if request.method == 'GET':
        flash('Enregistrement du compte admin' , 'info')
        return render_template('register.html')

    user = User(None, request.form['username'] , request.form['password'], request.form['email'], 1)
    users.insert(user.__dict__)
    flash('Admin successfully registered')
    return redirect(url_for('.login'))

app/templates/admin.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/spectrum.css"/>
<link rel="stylesheet" type="text/css" href="/static/css/admin.css"/>
{% endblock %}
{% block js_link -%}
	<script type="text/javascript" src="/static/js/vendor/require.min.js" data-main="/static/js/app/config/Init.js"></script>
{%- endblock %}

{% block body %}
	<header class="navbar navbar-fixed-top navbar-inverse" role="navigation"></header>
	<div id="main"></div>
	<div id="bubble"></div>
{% endblock %}

{% block js_script %}
<script type="text/javascript">
server_info = {{ server_info|safe }};
settings = {{ settings|safe }};
races = {{ races|safe }};
default_race = {{ config.PUBLIC_CONFIG|safe }};
{%- if stream_status %}
stream_status = {{ stream_status|safe }};
twitter_account = {{ twitter_account|safe }};
{% endif -%}
themes = {{ themes|safe }};
level = '{{ level }}';
is_admin = {{ is_admin|lower|safe }};
bucket = '{{ bucket|safe }}'
debugging = {{ config.DEBUG|lower|safe }};
designer = {{ config.DESIGNER|lower|safe }};
</script>
{% endblock %}

app/templates/home.html
{% extends "layout.html" %}
{% block css %}
<link rel="stylesheet" type="text/css" href="/static/css/admin.css"/>
<style type="text/css">
body {
    background: url("/static/img/bg_masked_50.png") repeat scroll 0 0 #595959;
}
</style>
{% endblock %}
{% block js_link %}
<script src="/static/js/vendor/socket.io.min.js"></script>
{% endblock %}

{%- block body %}
<div id="main" class="container section waiting-section">
    <div class="section-content">
        <div id="visualPing" class="pull-right" style="display: none;">
            Pong!
        </div>

        <div class="intro">
            <p class="pull-right"><a id="adminBtn" href="{{ url_for('admin.admin') }}" class="btn btn-blacky active">Administrez vos live</a></p>
            <h2>
                Bienvenue sur {{ app_title }} 
                <small>Le stream est actuellement <span id="status-stream" class="label label-default"></span></small>
            </h2>
            {{ app_desc|safe }}
        </div>
    </div>
</div>
{%- endblock %}

{%- block js_script %}
<script type="text/javascript">

var stream_status = {{ stream_status|safe }};
var stream_label = document.getElementById("status-stream");
if(stream_status.status == "stopped"){
    stream_label.className = "label label-danger";
    text = document.createTextNode('arrêté');
    stream_label.appendChild(text);
}else if(stream_status.status == "started"){
    stream_label.className = "label label-success";
    text = document.createTextNode('démarré');
    stream_label.appendChild(text);
}

var socket = io.connect("/shouts");
var visualPing = document.getElementById("visualPing");

socket.on("connect", function () {
    console.log("Connexion établie avec le serveur, %o", this);

    // ne devrait etre qu'un seul event ?
    socket.emit("join_only", "waiting");
    socket.emit("waiting", "A screen is waiting");

    socket.on("ping", function(msg){
        visualPing.style.display = "block";
        setTimeout(function(){
            visualPing.style.display = "none";
        }, 5000);
    });

    socket.on("gotourl", function(url){
        socket.emit("leave","waiting");
        document.location.href = url;
    });

    window.leave = function(){
        socket.emit("leave","waiting");
    }
    
    document.getElementById("adminBtn").onclick=function(){
        socket.emit("leave","waiting");
    };

});

window.onunload = function(){
    window.leave();
}

window.onbeforeunload = function(){
    window.leave();
}
</script>
{% endblock %}

app/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7 ui-mobile-rendering" lang="en"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8 ui-mobile-rendering" lang="en"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9 ui-mobile-rendering" lang="en"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js ui-mobile-rendering" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <title>{{ app_title }}</title>
    <meta name="description" content="Créez vos propres streams publics pour un affichage temps réel de messages SMS et de tweets sur de multiples supports: Vidéo-projection, Écran géant, TV connectée, Chromecast, appareils Android, et autres objets connectés">
    <!-- Mobile viewport optimized: h5bp.com/viewport -->
    <meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0, width=device-width">
    {% block css %}
    <link rel="stylesheet" type="text/css" href="/static/css/admin.css"/>
    {% endblock %}
    {% block js_link %}{% endblock %}
</head>
<body>
{%- with messages = get_flashed_messages(category_filter=["error"]) %}
    {% if messages %}
    <div class="container flashes">
        {% for message in messages %}
        <div class="alert alert-danger alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
        </div>
        {% endfor %}
    </div>
    {% endif %}
{% endwith -%}
{% block body %}{% endblock %}

{% block js_script %}{% endblock %}
</body>
</html>

app/templates/login.html
{% extends "layout.html" %}
{%- block body %}
<div id="main" class="section">
    <div class="section-content">
        <div class="page-header">
            <a href="{{ url_for('user.register') }}" class="pull-right btn btn-blacky">Register</a>
            <h2>Autentification <small></small></h2>
        </div>

        <form action="" method="post" role="form" class="form-horizontal">
            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Login</label>
                <div class="col-sm-4">
                    <input type="text" id="username" name="username" class="form-control" placeholder="Entrez votre login">
                </div>
            </div>
         
            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-4">
                    <input type="password" id="password" name="password" class="form-control" placeholder="Entrez votre mot de passe">
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button type="submit" class="btn btn-success">Connexion</button>
                    <a href="{{ url_for('home') }}" class="btn btn-blacky">Annuler</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/register.html
{% extends "layout.html" %}
{%- block body %}
<div id="main" class="section">
    <div class="section-content">
        <div class="page-header">
            <a href="{{ url_for('user.login') }}" class="pull-right btn btn-blacky">Login</a>
            <h2>Création de compte<small></small></h2>
        </div>

        <form action="" method="post" role="form" class="form-horizontal">

            <div class="form-group">
                <label for="username" class="col-sm-2 control-label">Login</label>
                <div class="col-sm-4">
                    <input type="text" id="username" name="username" class="form-control" placeholder="Entrez votre login" value="{{ request.form.username }}" required>
                </div>
            </div>

            <div class="form-group">
                <label for="password" class="col-sm-2 control-label">Password</label>
                <div class="col-sm-4">
                    <input type="password" id="password" name="password" class="form-control" placeholder="Entrez votre mot de passe" value="{{ request.form.password }}" required>
                </div>
            </div>

            <div class="form-group">
                <label for="email" class="col-sm-2 control-label">Email</label>
                <div class="col-sm-4">
                    <input type="email" id="email" name="email" class="form-control" placeholder="Entrez votre email" value="{{ request.form.username }}" required>
                </div>
            </div>

            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-4">
                    <button type="submit" class="btn btn-success">Inscription</button>
                    <a href="{{ url_for('home') }}" class="btn btn-blacky">Annuler</a>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}